name: Bot CI

on:
  push:
    path:
      - 'bot/**'
      - 'common/**'
      - 'bot.Dockerfile'
      - 'checkstyle.xml'
      - 'parent-project/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Maven project
        run: cd parent-project | mvn package -pl bot -am

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: cd parent-project | docker build --file bot.Dockerfile -t bot:latest .

      - name: Push Docker image to Docker Hub
        run: cd parent-project | docker push bot:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Run check style
        run: |
          mvn -pl bot -am checkstyle:check