name: Bot CI

on:
  push:
    path:
      - 'bot/**'
      - 'common/**'
      - 'bot.Dockerfile'
      - 'checkstyle.xml'
      - 'parent-project/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project
        run: cd parent-project && mvn package -pl bot -am

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        uses: actions/github-script@v6
        id: lowercase_repo
        with:
          result-encoding: string
          script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()

      - name: Build Docker image
        run: cd parent-project && docker build --file bot.Dockerfile -t ${{ steps.lowercase_repo.outputs.result }}/bot:latest .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{ steps.lowercase_repo.outputs.result }}/bot:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Run check style
        run: cd parent-project && mvn -pl bot -am checkstyle:check